# This is the SAM template for deploying the lambdas.
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for deploying all lambdas
Resources:
  UploadToS3Lambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ../../lambdas/fetch-s3-data/fetch-s3-data.zip
      Role: arn:aws:iam::703085461864:role/lambdas3
      FunctionName: fetch-s3-data
      Timeout: 120
      MemorySize: 128
      Environment:
        Variables:
          Author: nasara
      Tags:
        project: aws-serverless-demo
        type: lambda